# Dutch to Spanish Translation Tool

# A dictionary containing Dutch words and their Spanish translations.
translations = {
    'hallo': 'hola',
    'goedemorgen': 'buenos días',
    'tot ziens': 'adiós',
    'dank je': 'gracias',
    'alsjeblieft': 'por favor',
    'ja': 'sí',
    'nee': 'no',
    'misschien': 'quizás',
    'huis': 'casa',
    'auto': 'coche',
    'boek': 'libro',
    'stoel': 'silla',
    'tafel': 'mesa',
    'vriend': 'amigo',
    'vriendin': 'amiga',
    'werk': 'trabajo',
    'school': 'escuela',
    'team': 'equipo',
    'dag': 'día',
    'maand': 'mes',
    'jaar': 'año',
    'lekker': 'rico',
    'water': 'agua',
    'eten': 'comida',
    'drinken': 'beber',
    'gezondheid': 'salud',
    'gezellig': 'acogedor',
    'mooi': 'bonito',
    'leuk': 'divertido',
    'saai': 'aburrido',
    'interessant': 'interesante',
    'telefoon': 'teléfono',
    'computer': 'computadora',
    'internet': 'internet',
    'televisie': 'televisión',
    'film': 'película',
    'muziek': 'música',
    'letter': 'letra',
    'woord': 'palabra',
    'zin': 'oración',
    'vraag': 'pregunta',
    'antwoord': 'respuesta',
    'onderwijs': 'educación',
    'leer': 'aprender',
    'onderwijzen': 'enseñar',
    'woordenschat': 'vocabulario',
    'woordenboek': 'diccionario',
    'grammatica': 'gramática',
    'cultuur': 'cultura',
    'taal': 'idioma',
    'land': 'país',
    'wereld': 'mundo',
    'mensen': 'personas',
    'kind': 'niño',
    'kinderen': 'niños',
    'familie': 'familia',
    'huisdier': 'mascota',
    'kat': 'gato',
    'hond': 'perro',
    'vogel': 'pájaro',
    'vis': 'pez',
    'dier': 'animal',
    'plant': 'planta',
    'berg': 'montaña',
    'zee': 'mar',
    'rivier': 'río',
    'woud': 'bos',
    'lucht': 'aire',
    'zon': 'sol',
    'maan': 'luna',
    'ster': 'estrella',
    'wind': 'viento',
    'regen': 'lluvia',
    'sneeuw': 'nieve',
    'grond': 'tierra',
    'steen': 'piedra',
    'straat': 'calle',
    'plaats': 'lugar',
    'stad': 'ciudad',
    'dorp': 'pueblo',
    'gemeente': 'municipio',
    'regio': 'región',
    'provincie': 'provincia',
    'hoofd': 'cabeza',
    'lichaam': 'cuerpo',
    'geest': 'mente',
    'hart': 'corazón',
    'ziel': 'alma',
    'voorkeur': 'preferencia',
    'gevoel': 'sentimiento',
    'idee': 'idea',
    'plan': 'plan',
    'project': 'proyecto',
    'droom': 'sueño',
    'tijd': 'tiempo',
    'moment': 'momento',
    'ervaring': 'experiencia',
    'gevoelens': 'sentimientos',
    'herinnering': 'recuerdo',
    'verlangen': 'deseo',
    'blik': 'mirada',
    'stem': 'voz',
    'geluid': 'sonido',
    'kleur': 'color',
    'licht': 'luz',
    'donker': 'oscuro',
    'warm': 'caliente',
    'koud': 'frío',
    'smaak': 'sabor',
    'gezondheid': 'salud',
    'geluk': 'suerte',
    'rijk': 'rico',
    'arm': 'pobre',
    'war': 'guerra',
    'vred': 'paz',
    'liefde': 'amor',
    'haat': 'odio',
    'respect': 'respeto',
    'kwaad': 'mal',
    'goed': 'bueno',
    'slecht': 'malo',
    'echt': 'auténtico',
    'vals': 'falso',
    'moed': 'valentía',
    'angst': 'miedo',
    'spelen': 'jugar',
    'werken': 'trabajar',
    'studeren': 'estudiar',
    'lezen': 'leer',
    'schrijven': 'escribir',
    'luisteren': 'escuchar',
    'praten': 'hablar',
    'denken': 'pensar',
    'trouwen': 'casarse',
    'scheiden': 'divorciarse',
    'genieten': 'disfrutar',
    'verliezen': 'perder',
    'winnen': 'ganar',
    'veranderen': 'cambiar',
    'blijven': 'quedarse',
}

# Function to translate words from Dutch to Spanish

def translate(word):
    return translations.get(word, "Translation not found")


# Example usage
if __name__ == '__main__':
    word = input('Enter a Dutch word to translate: ')
    print(f'Translated to Spanish: {translate(word)}')